builds:
  - binary: redalert
    go: 1.27.1
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
