version: 2

builds:
  - id: redalert
    main: .
    binary: redalert
    ldflags:
      - -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
