version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.27.1
      - image: postgres:9.5
        environment:
          POSTGRES_PASSWORD: ""
    environment:
      DOCKER_API_VERSION: "1.20"
      POSTGRES_IMAGE: "postgres:9.5"
    steps:
      - checkout
      - run: go mod download
      - run: go mod tidy
      - run: git diff --exit-code -- go.mod go.sum
      - run: go test ./...
      - run: go build ./...
      - run: make build

workflows:
  version: 2
  build:
    jobs:
      - build
