// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	ListChecksRequest
	ListChecksResponse
	Check
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Check_Status int32

const (
	Check_UNKNOWN   Check_Status = 0
	Check_NORMAL    Check_Status = 1
	Check_FAILING   Check_Status = 2
	Check_RECOVERED Check_Status = 3
)

var Check_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "FAILING",
	3: "RECOVERED",
}
var Check_Status_value = map[string]int32{
	"UNKNOWN":   0,
	"NORMAL":    1,
	"FAILING":   2,
	"RECOVERED": 3,
}

func (x Check_Status) String() string {
	return proto.EnumName(Check_Status_name, int32(x))
}
func (Check_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type ListChecksRequest struct {
}

func (m *ListChecksRequest) Reset()                    { *m = ListChecksRequest{} }
func (m *ListChecksRequest) String() string            { return proto.CompactTextString(m) }
func (*ListChecksRequest) ProtoMessage()               {}
func (*ListChecksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ListChecksResponse struct {
	Members []*Check `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *ListChecksResponse) Reset()                    { *m = ListChecksResponse{} }
func (m *ListChecksResponse) String() string            { return proto.CompactTextString(m) }
func (*ListChecksResponse) ProtoMessage()               {}
func (*ListChecksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListChecksResponse) GetMembers() []*Check {
	if m != nil {
		return m.Members
	}
	return nil
}

type Check struct {
	ID     string       `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	Name   string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Status Check_Status `protobuf:"varint,3,opt,name=status,enum=service.Check_Status" json:"status,omitempty"`
}

func (m *Check) Reset()                    { *m = Check{} }
func (m *Check) String() string            { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()               {}
func (*Check) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*ListChecksRequest)(nil), "service.ListChecksRequest")
	proto.RegisterType((*ListChecksResponse)(nil), "service.ListChecksResponse")
	proto.RegisterType((*Check)(nil), "service.Check")
	proto.RegisterEnum("service.Check_Status", Check_Status_name, Check_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for RedalertService service

type RedalertServiceClient interface {
	ListChecks(ctx context.Context, in *ListChecksRequest, opts ...grpc.CallOption) (*ListChecksResponse, error)
}

type redalertServiceClient struct {
	cc *grpc.ClientConn
}

func NewRedalertServiceClient(cc *grpc.ClientConn) RedalertServiceClient {
	return &redalertServiceClient{cc}
}

func (c *redalertServiceClient) ListChecks(ctx context.Context, in *ListChecksRequest, opts ...grpc.CallOption) (*ListChecksResponse, error) {
	out := new(ListChecksResponse)
	err := grpc.Invoke(ctx, "/service.RedalertService/ListChecks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RedalertService service

type RedalertServiceServer interface {
	ListChecks(context.Context, *ListChecksRequest) (*ListChecksResponse, error)
}

func RegisterRedalertServiceServer(s *grpc.Server, srv RedalertServiceServer) {
	s.RegisterService(&_RedalertService_serviceDesc, srv)
}

func _RedalertService_ListChecks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChecksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).ListChecks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.RedalertService/ListChecks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).ListChecks(ctx, req.(*ListChecksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedalertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.RedalertService",
	HandlerType: (*RedalertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListChecks",
			Handler:    _RedalertService_ListChecks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4f, 0x83, 0x40,
	0x10, 0x86, 0x0b, 0x28, 0xa4, 0xd3, 0x14, 0x71, 0x8c, 0x09, 0xa9, 0x17, 0xc3, 0x89, 0x8b, 0x1c,
	0xf0, 0xac, 0x49, 0x53, 0xb0, 0x21, 0xe2, 0x92, 0x6c, 0xa3, 0x26, 0xde, 0x68, 0x9d, 0x44, 0xa2,
	0x94, 0xca, 0x6c, 0xfd, 0x2f, 0xfe, 0x5b, 0xeb, 0xd2, 0xfa, 0x11, 0xbd, 0xed, 0x3e, 0xcf, 0x9b,
	0x99, 0xcc, 0x0b, 0x43, 0xa6, 0xf6, 0xad, 0x5a, 0x50, 0xb4, 0x6a, 0x1b, 0xd5, 0xa0, 0xb3, 0xfd,
	0x06, 0x47, 0x70, 0x98, 0x57, 0xac, 0x26, 0x4f, 0xb4, 0x78, 0x66, 0x49, 0xaf, 0x6b, 0x62, 0x15,
	0x5c, 0x02, 0xfe, 0x84, 0xbc, 0x6a, 0x96, 0x4c, 0x18, 0x82, 0x53, 0x53, 0x3d, 0xa7, 0x96, 0x7d,
	0xe3, 0xd4, 0x0a, 0x07, 0xb1, 0x1b, 0xed, 0x86, 0xea, 0xa4, 0xdc, 0xe9, 0xe0, 0xdd, 0x80, 0x7d,
	0x8d, 0xd0, 0x05, 0x33, 0x4b, 0x36, 0x71, 0x23, 0xec, 0x4b, 0xb3, 0x4a, 0x10, 0x61, 0x6f, 0x59,
	0xd6, 0xe4, 0x9b, 0x9a, 0xe8, 0x37, 0x9e, 0x81, 0xcd, 0xaa, 0x54, 0x6b, 0xf6, 0xad, 0x0d, 0x75,
	0xe3, 0xe3, 0xdf, 0x63, 0xa3, 0x99, 0x96, 0x72, 0x1b, 0x0a, 0x2e, 0xc0, 0xee, 0x08, 0x0e, 0xc0,
	0xb9, 0x15, 0xd7, 0xa2, 0xb8, 0x17, 0x5e, 0x0f, 0x01, 0x6c, 0x51, 0xc8, 0x9b, 0x71, 0xee, 0x19,
	0x9f, 0xe2, 0x6a, 0x9c, 0xe5, 0x99, 0x98, 0x7a, 0x26, 0x0e, 0xa1, 0x2f, 0xd3, 0x49, 0x71, 0x97,
	0xca, 0x34, 0xf1, 0xac, 0xf8, 0x01, 0x0e, 0x24, 0x3d, 0x96, 0x2f, 0xd4, 0xaa, 0x59, 0xb7, 0x06,
	0xa7, 0x00, 0xdf, 0xe7, 0xe2, 0xe8, 0x6b, 0xfd, 0x9f, 0x62, 0x46, 0x27, 0xff, 0xba, 0xae, 0x9f,
	0xa0, 0x37, 0xb7, 0x75, 0xb9, 0xe7, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x9f, 0x76, 0x49,
	0x6d, 0x01, 0x00, 0x00,
}
