// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package servicepb is a generated protocol buffer package.

It is generated from these files:

	service.proto

It has these top-level messages:

	CheckAddRequest
	CheckAddResponse
	CheckListRequest
	CheckListResponse
	CheckEnableRequest
	CheckEnableResponse
	CheckDisableRequest
	CheckDisableResponse
	EventListRequest
	EventListResponse
	Event
	Metric
	Check
*/
package servicepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Check_Status int32

const (
	Check_DISABLED   Check_Status = 0
	Check_UNKNOWN    Check_Status = 1
	Check_FAILING    Check_Status = 2
	Check_SUCCESSFUL Check_Status = 3
)

var Check_Status_name = map[int32]string{
	0: "DISABLED",
	1: "UNKNOWN",
	2: "FAILING",
	3: "SUCCESSFUL",
}
var Check_Status_value = map[string]int32{
	"DISABLED":   0,
	"UNKNOWN":    1,
	"FAILING":    2,
	"SUCCESSFUL": 3,
}

func (x Check_Status) String() string {
	return proto.EnumName(Check_Status_name, int32(x))
}
func (Check_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{12, 0} }

type CheckAddRequest struct {
	Destination string `protobuf:"bytes,1,opt,name=destination" json:"destination,omitempty"`
	Json        string `protobuf:"bytes,2,opt,name=json" json:"json,omitempty"`
}

func (m *CheckAddRequest) Reset()                    { *m = CheckAddRequest{} }
func (m *CheckAddRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckAddRequest) ProtoMessage()               {}
func (*CheckAddRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CheckAddRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *CheckAddRequest) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type CheckAddResponse struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids" json:"ids,omitempty"`
}

func (m *CheckAddResponse) Reset()                    { *m = CheckAddResponse{} }
func (m *CheckAddResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckAddResponse) ProtoMessage()               {}
func (*CheckAddResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CheckAddResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type CheckListRequest struct {
}

func (m *CheckListRequest) Reset()                    { *m = CheckListRequest{} }
func (m *CheckListRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckListRequest) ProtoMessage()               {}
func (*CheckListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CheckListResponse struct {
	Members []*Check `protobuf:"bytes,1,rep,name=members" json:"members,omitempty"`
}

func (m *CheckListResponse) Reset()                    { *m = CheckListResponse{} }
func (m *CheckListResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckListResponse) ProtoMessage()               {}
func (*CheckListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CheckListResponse) GetMembers() []*Check {
	if m != nil {
		return m.Members
	}
	return nil
}

type CheckEnableRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *CheckEnableRequest) Reset()                    { *m = CheckEnableRequest{} }
func (m *CheckEnableRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckEnableRequest) ProtoMessage()               {}
func (*CheckEnableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CheckEnableRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CheckEnableResponse struct {
}

func (m *CheckEnableResponse) Reset()                    { *m = CheckEnableResponse{} }
func (m *CheckEnableResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckEnableResponse) ProtoMessage()               {}
func (*CheckEnableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CheckDisableRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *CheckDisableRequest) Reset()                    { *m = CheckDisableRequest{} }
func (m *CheckDisableRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckDisableRequest) ProtoMessage()               {}
func (*CheckDisableRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CheckDisableRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CheckDisableResponse struct {
}

func (m *CheckDisableResponse) Reset()                    { *m = CheckDisableResponse{} }
func (m *CheckDisableResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckDisableResponse) ProtoMessage()               {}
func (*CheckDisableResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type EventListRequest struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *EventListRequest) Reset()                    { *m = EventListRequest{} }
func (m *EventListRequest) String() string            { return proto.CompactTextString(m) }
func (*EventListRequest) ProtoMessage()               {}
func (*EventListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EventListRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type EventListResponse struct {
	Events []*Event `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
}

func (m *EventListResponse) Reset()                    { *m = EventListResponse{} }
func (m *EventListResponse) String() string            { return proto.CompactTextString(m) }
func (*EventListResponse) ProtoMessage()               {}
func (*EventListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EventListResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type Event struct {
	Time     string            `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Tags     map[string]string `protobuf:"bytes,2,rep,name=tags" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Messages []string          `protobuf:"bytes,3,rep,name=messages" json:"messages,omitempty"`
	Metrics  []*Metric         `protobuf:"bytes,4,rep,name=metrics" json:"metrics,omitempty"`
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Event) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Event) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Event) GetMessages() []string {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (m *Event) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Metric struct {
	Name    string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value   float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Present bool    `protobuf:"varint,3,opt,name=present" json:"present,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Metric) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

type Check struct {
	ID      string       `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name    string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type    string       `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Status  Check_Status `protobuf:"varint,4,opt,name=status,enum=servicepb.Check_Status" json:"status,omitempty"`
	Enabled bool         `protobuf:"varint,5,opt,name=enabled" json:"enabled,omitempty"`
}

func (m *Check) Reset()                    { *m = Check{} }
func (m *Check) String() string            { return proto.CompactTextString(m) }
func (*Check) ProtoMessage()               {}
func (*Check) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Check) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Check) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Check) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Check) GetStatus() Check_Status {
	if m != nil {
		return m.Status
	}
	return Check_DISABLED
}

func (m *Check) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*CheckAddRequest)(nil), "servicepb.CheckAddRequest")
	proto.RegisterType((*CheckAddResponse)(nil), "servicepb.CheckAddResponse")
	proto.RegisterType((*CheckListRequest)(nil), "servicepb.CheckListRequest")
	proto.RegisterType((*CheckListResponse)(nil), "servicepb.CheckListResponse")
	proto.RegisterType((*CheckEnableRequest)(nil), "servicepb.CheckEnableRequest")
	proto.RegisterType((*CheckEnableResponse)(nil), "servicepb.CheckEnableResponse")
	proto.RegisterType((*CheckDisableRequest)(nil), "servicepb.CheckDisableRequest")
	proto.RegisterType((*CheckDisableResponse)(nil), "servicepb.CheckDisableResponse")
	proto.RegisterType((*EventListRequest)(nil), "servicepb.EventListRequest")
	proto.RegisterType((*EventListResponse)(nil), "servicepb.EventListResponse")
	proto.RegisterType((*Event)(nil), "servicepb.Event")
	proto.RegisterType((*Metric)(nil), "servicepb.Metric")
	proto.RegisterType((*Check)(nil), "servicepb.Check")
	proto.RegisterEnum("servicepb.Check_Status", Check_Status_name, Check_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RedalertService service

type RedalertServiceClient interface {
	// CheckList lists all the checks in configuration
	CheckList(ctx context.Context, in *CheckListRequest, opts ...grpc.CallOption) (*CheckListResponse, error)
	// CheckEnable enables a check
	CheckEnable(ctx context.Context, in *CheckEnableRequest, opts ...grpc.CallOption) (*CheckEnableResponse, error)
	// CheckDisable disables a check
	CheckDisable(ctx context.Context, in *CheckDisableRequest, opts ...grpc.CallOption) (*CheckDisableResponse, error)
	CheckAdd(ctx context.Context, in *CheckAddRequest, opts ...grpc.CallOption) (*CheckAddResponse, error)
	// EventList lists retained events for a check.
	EventList(ctx context.Context, in *EventListRequest, opts ...grpc.CallOption) (*EventListResponse, error)
}

type redalertServiceClient struct {
	cc *grpc.ClientConn
}

func NewRedalertServiceClient(cc *grpc.ClientConn) RedalertServiceClient {
	return &redalertServiceClient{cc}
}

func (c *redalertServiceClient) CheckList(ctx context.Context, in *CheckListRequest, opts ...grpc.CallOption) (*CheckListResponse, error) {
	out := new(CheckListResponse)
	err := grpc.Invoke(ctx, "/servicepb.RedalertService/CheckList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redalertServiceClient) CheckEnable(ctx context.Context, in *CheckEnableRequest, opts ...grpc.CallOption) (*CheckEnableResponse, error) {
	out := new(CheckEnableResponse)
	err := grpc.Invoke(ctx, "/servicepb.RedalertService/CheckEnable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redalertServiceClient) CheckDisable(ctx context.Context, in *CheckDisableRequest, opts ...grpc.CallOption) (*CheckDisableResponse, error) {
	out := new(CheckDisableResponse)
	err := grpc.Invoke(ctx, "/servicepb.RedalertService/CheckDisable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redalertServiceClient) CheckAdd(ctx context.Context, in *CheckAddRequest, opts ...grpc.CallOption) (*CheckAddResponse, error) {
	out := new(CheckAddResponse)
	err := grpc.Invoke(ctx, "/servicepb.RedalertService/CheckAdd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redalertServiceClient) EventList(ctx context.Context, in *EventListRequest, opts ...grpc.CallOption) (*EventListResponse, error) {
	out := new(EventListResponse)
	err := grpc.Invoke(ctx, "/servicepb.RedalertService/EventList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RedalertService service

type RedalertServiceServer interface {
	// CheckList lists all the checks in configuration
	CheckList(context.Context, *CheckListRequest) (*CheckListResponse, error)
	// CheckEnable enables a check
	CheckEnable(context.Context, *CheckEnableRequest) (*CheckEnableResponse, error)
	// CheckDisable disables a check
	CheckDisable(context.Context, *CheckDisableRequest) (*CheckDisableResponse, error)
	CheckAdd(context.Context, *CheckAddRequest) (*CheckAddResponse, error)
	// EventList lists retained events for a check.
	EventList(context.Context, *EventListRequest) (*EventListResponse, error)
}

func RegisterRedalertServiceServer(s *grpc.Server, srv RedalertServiceServer) {
	s.RegisterService(&_RedalertService_serviceDesc, srv)
}

func _RedalertService_CheckList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).CheckList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicepb.RedalertService/CheckList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).CheckList(ctx, req.(*CheckListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedalertService_CheckEnable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckEnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).CheckEnable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicepb.RedalertService/CheckEnable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).CheckEnable(ctx, req.(*CheckEnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedalertService_CheckDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).CheckDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicepb.RedalertService/CheckDisable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).CheckDisable(ctx, req.(*CheckDisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedalertService_CheckAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).CheckAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicepb.RedalertService/CheckAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).CheckAdd(ctx, req.(*CheckAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedalertService_EventList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedalertServiceServer).EventList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicepb.RedalertService/EventList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedalertServiceServer).EventList(ctx, req.(*EventListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RedalertService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "servicepb.RedalertService",
	HandlerType: (*RedalertServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckList",
			Handler:    _RedalertService_CheckList_Handler,
		},
		{
			MethodName: "CheckEnable",
			Handler:    _RedalertService_CheckEnable_Handler,
		},
		{
			MethodName: "CheckDisable",
			Handler:    _RedalertService_CheckDisable_Handler,
		},
		{
			MethodName: "CheckAdd",
			Handler:    _RedalertService_CheckAdd_Handler,
		},
		{
			MethodName: "EventList",
			Handler:    _RedalertService_EventList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 628 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5f, 0x6f, 0xd3, 0x30,
	0x10, 0x5f, 0x92, 0xb5, 0x6b, 0xaf, 0xfb, 0x93, 0x99, 0x01, 0x51, 0x36, 0x46, 0x65, 0x0d, 0xa9,
	0x02, 0xa9, 0x48, 0xe3, 0x01, 0x34, 0x84, 0x60, 0xac, 0xdd, 0x56, 0xd1, 0x15, 0x91, 0x30, 0xf1,
	0xec, 0x2e, 0xa7, 0x11, 0xb6, 0xa6, 0x21, 0xf6, 0x26, 0xf5, 0x53, 0xf0, 0xad, 0x78, 0xe2, 0x43,
	0x21, 0x3b, 0x4e, 0x96, 0xa4, 0x1d, 0x12, 0x6f, 0xbe, 0xbb, 0xdf, 0xef, 0xe7, 0xbb, 0xf3, 0x9d,
	0x61, 0x8d, 0x63, 0x72, 0x1b, 0x5e, 0x60, 0x37, 0x4e, 0xa6, 0x62, 0x4a, 0x9a, 0xda, 0x8c, 0xc7,
	0xf4, 0x04, 0x36, 0x8e, 0xbe, 0xe3, 0xc5, 0xd5, 0x61, 0x10, 0x78, 0xf8, 0xf3, 0x06, 0xb9, 0x20,
	0x6d, 0x68, 0x05, 0xc8, 0x45, 0x18, 0x31, 0x11, 0x4e, 0x23, 0xc7, 0x68, 0x1b, 0x9d, 0xa6, 0x57,
	0x74, 0x11, 0x02, 0xcb, 0x3f, 0xf8, 0x34, 0x72, 0x4c, 0x15, 0x52, 0x67, 0xba, 0x07, 0xf6, 0x9d,
	0x10, 0x8f, 0xa7, 0x11, 0x47, 0x62, 0x83, 0x15, 0x06, 0xdc, 0x31, 0xda, 0x56, 0xa7, 0xe9, 0xc9,
	0x23, 0x25, 0x1a, 0x35, 0x0c, 0xb9, 0xd0, 0xf7, 0xd1, 0xf7, 0xb0, 0x59, 0xf0, 0x69, 0xea, 0x73,
	0x58, 0x99, 0xe0, 0x64, 0x8c, 0x49, 0x4a, 0x6f, 0xed, 0xdb, 0xdd, 0x3c, 0xe9, 0xae, 0x82, 0x7b,
	0x19, 0x80, 0xee, 0x01, 0x51, 0x9e, 0x7e, 0xc4, 0xc6, 0xd7, 0x98, 0x95, 0xb1, 0x0e, 0xe6, 0xa0,
	0xa7, 0xb3, 0x37, 0x07, 0x3d, 0xfa, 0x10, 0x1e, 0x94, 0x50, 0xe9, 0x45, 0xf4, 0x99, 0x76, 0xf7,
	0x42, 0xfe, 0x2f, 0xf6, 0x23, 0xd8, 0x2a, 0xc3, 0x34, 0x9d, 0x82, 0xdd, 0xbf, 0xc5, 0x48, 0x14,
	0x0a, 0x9a, 0xe3, 0xbe, 0x83, 0xcd, 0x02, 0x46, 0x17, 0xd8, 0x81, 0x3a, 0x4a, 0xe7, 0xa2, 0xfa,
	0x14, 0xda, 0xd3, 0x71, 0xfa, 0xdb, 0x84, 0x9a, 0xf2, 0xc8, 0xbe, 0x8b, 0x70, 0x82, 0x5a, 0x5a,
	0x9d, 0x49, 0x17, 0x96, 0x05, 0xbb, 0xe4, 0x8e, 0xa9, 0x54, 0xdc, 0xaa, 0x4a, 0xf7, 0x2b, 0xbb,
	0xe4, 0xfd, 0x48, 0x24, 0x33, 0x4f, 0xe1, 0x88, 0x0b, 0x8d, 0x09, 0x72, 0xce, 0x2e, 0x91, 0x3b,
	0x96, 0x7a, 0x98, 0xdc, 0x26, 0x2f, 0x64, 0xd3, 0x45, 0x12, 0x5e, 0x70, 0x67, 0x59, 0xc9, 0x6d,
	0x16, 0xe4, 0xce, 0x54, 0xc4, 0xcb, 0x10, 0xe4, 0x40, 0x0a, 0x09, 0x16, 0x30, 0xc1, 0x9c, 0x9a,
	0x42, 0xef, 0xce, 0x5d, 0x7e, 0xa6, 0x01, 0x69, 0x02, 0x39, 0xde, 0x7d, 0x0d, 0xcd, 0x3c, 0x2f,
	0x39, 0x25, 0x57, 0x38, 0xd3, 0x45, 0xc9, 0x23, 0xd9, 0x82, 0xda, 0x2d, 0xbb, 0xbe, 0x41, 0x3d,
	0x60, 0xa9, 0x71, 0x60, 0xbe, 0x31, 0xdc, 0xb7, 0xb0, 0x56, 0xd2, 0xfc, 0x1f, 0x32, 0x1d, 0x42,
	0x3d, 0x2d, 0x42, 0x36, 0x32, 0x62, 0x77, 0x8d, 0x94, 0xe7, 0x32, 0xcf, 0xd0, 0x3c, 0xe2, 0xc0,
	0x4a, 0x9c, 0x20, 0xc7, 0x48, 0x38, 0x56, 0xdb, 0xe8, 0x34, 0xbc, 0xcc, 0xa4, 0x7f, 0x0c, 0xa8,
	0xa9, 0x91, 0xa8, 0xbe, 0x77, 0xae, 0x6e, 0x16, 0xd4, 0xe5, 0xd3, 0xcd, 0x62, 0x74, 0x2c, 0xfd,
	0x74, 0xb3, 0x18, 0xc9, 0x4b, 0xa8, 0x73, 0xc1, 0xc4, 0x8d, 0xec, 0xb6, 0xd1, 0x59, 0xdf, 0x7f,
	0x5c, 0x1d, 0xf1, 0xae, 0xaf, 0xc2, 0x9e, 0x86, 0xc9, 0x64, 0x50, 0x4d, 0x6f, 0xe0, 0xd4, 0xd2,
	0x64, 0xb4, 0x49, 0x3f, 0x40, 0x3d, 0xc5, 0x92, 0x55, 0x68, 0xf4, 0x06, 0xfe, 0xe1, 0xc7, 0x61,
	0xbf, 0x67, 0x2f, 0x91, 0x16, 0xac, 0x9c, 0x8f, 0x3e, 0x8d, 0x3e, 0x7f, 0x1b, 0xd9, 0x86, 0x34,
	0x8e, 0x0f, 0x07, 0xc3, 0xc1, 0xe8, 0xc4, 0x36, 0xc9, 0x3a, 0x80, 0x7f, 0x7e, 0x74, 0xd4, 0xf7,
	0xfd, 0xe3, 0xf3, 0xa1, 0x6d, 0xed, 0xff, 0xb2, 0x60, 0xc3, 0xc3, 0x80, 0x5d, 0x63, 0x22, 0xfc,
	0x34, 0x0d, 0x72, 0x0a, 0xcd, 0x7c, 0x33, 0xc9, 0x76, 0x35, 0xbb, 0xc2, 0xc8, 0xbb, 0x3b, 0x8b,
	0x83, 0x7a, 0x49, 0x96, 0xc8, 0x08, 0x5a, 0x85, 0xe5, 0x23, 0x4f, 0xaa, 0xf0, 0xd2, 0xea, 0xba,
	0xbb, 0xf7, 0x85, 0x73, 0xbd, 0x2f, 0xb0, 0x5a, 0x5c, 0x47, 0x32, 0xc7, 0x28, 0xaf, 0xb3, 0xfb,
	0xf4, 0xde, 0x78, 0x2e, 0xd9, 0x87, 0x46, 0xf6, 0x81, 0x11, 0xb7, 0x0a, 0xbf, 0xfb, 0x1e, 0xdd,
	0xed, 0x85, 0xb1, 0x5c, 0xe6, 0x14, 0x9a, 0xf9, 0xb2, 0x97, 0x7a, 0x56, 0xfd, 0x26, 0xdc, 0x9d,
	0xc5, 0xc1, 0x4c, 0x69, 0x5c, 0x57, 0x9f, 0xf5, 0xab, 0xbf, 0x03, 0x00, 0xa7, 0x43, 0x35, 0xed,
	0xbd, 0x05, 0x00, 0x00,
}
